version: '3.8'

services:
  postgres:
    container_name: cloud-files
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cloud
    volumes:
      - ./data/cloud:/data/postgres
